version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
  nginx:
    container_name: nginx-gigi
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api
      - client
  api:
    container_name: api-gigi
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - JWTSECRET=mySecret
      - MONGOURI=mongodb://mongo:27017/shop
      - TZ=Asia/Singapore

  client:
    stdin_open: true
    container_name: client-gigi
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongodb-data:
