# FROM nginx:1.16.0-alpine
# FROM valian/docker-nginx-auto-ssl
# COPY ./nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

FROM nginx:1.16.0-alpine
COPY ./default.conf /etc/nginx/conf.d/default.conf